app/routes/auth.py
# Handles Signup and Login
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, current_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from models import db, User

auth_bp = Blueprint("auth", __name__)

@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        # Grab all form fields
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        faculty = request.form["faculty"]
        email = request.form["email"]
        password = request.form["password"]

        # Check if user already exists
        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            flash("Email already exists. Please log in instead!", "warning")
            return redirect(url_for("auth.login"))


        # Hash the password
        password_hash = generate_password_hash(password)

        new_user = User (
            first_name=first_name,
            last_name=last_name,
            faculty=faculty,
            email=email,
            password_hash=password_hash
        )

        try:
            db.session.add(new_user)
            db.session.commit()
            flash("Account created successfully. Please log in.", "success")
            return redirect(url_for("auth.login"))
        except Exception as e:
            db.session.rollback()
            flash(f"There was an issue in signing you up: {e}", "danger")
            return redirect(url_for("auth.signup"))
    else:
        # Show all users
        users = User.query.order_by(User.date_joined).all()
        return render_template("/signup.html", users=users)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash(f"You are already logged in!", "info")
        return redirect(url_for("index"))

    if request.method == "POST":
        session.permanent = True
        email = request.form["email"]
        password = request.form["password"]

        # Look up for the user
        user = User.query.filter_by(email=email).first()
        
        if not user:
            flash("No account found with that email.", "danger")
            return redirect(url_for("auth.signup"))

        # If found → check password
        if not check_password_hash(user.password_hash, password):
            flash("Incorrect password. Please try again.", "danger")
            return redirect(url_for("auth.login"))

        # If correct → log them in
        login_user(user, remember=True)
        # session["user"] = user.id
        flash(f"Welcome back, {user.first_name}!", "success")

        # Redirect to dashboard or home
        next_page = request.args.get("next")
        return redirect(next_page or url_for("index"))  # or homepage

    # For GET request → render the login page
    return render_template("login.html")


@auth_bp.route("/logout")
def logout():
    if current_user.is_authenticated:
        flash(f"You have been logged out, {current_user.first_name}.", "info")
        logout_user()
    else:
        flash("You are already logged out.", "warning")
    return redirect(url_for("auth.login"))

app/routes/books.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_required, current_user, login_user

from models import db, Book, BookRequest, Comments, Reply


books_bp = Blueprint("books", __name__)

@books_bp.route("/book_details/<int:book_id>", methods=["GET", "POST"])
@login_required
def book_details(book_id):
    book = Book.query.get_or_404(book_id)
    return render_template("book-details.html", book=book)


@books_bp.route("/book/<int:book_id>/comments", methods=["POST"])
@login_required
def add_comment(book_id):
    book = Book.query.get_or_404(book_id)
    content = request.form.get("comment_content", "").strip()
    
    if content:
        comment = Comments(
            comment_content = content,
            user_id = current_user.id,
            book_id = book.id
        )
        db.session.add(comment) 
        db.session.commit()
        flash("Comment Added!", "success")
    return redirect(url_for('books.book_details', book_id=book.id)) 


@books_bp.route("/book/<int:comment_id>/reply", methods=["POST"])
@login_required
def reply(comment_id):
    comment = Comments.query.get_or_404(comment_id)

    book = comment.book

    content = request.form.get("reply_content", "").strip()

    if content:
        new_reply = Reply(
            reply_content = content,
            comment_id = comment.id,
            user_id = current_user.id,
        )

        db.session.add(reply)
        db.session.commit()
        flash("Reply Added!", "success")
    return redirect(url_for('books.book_details', book_id=book.id))



@books_bp.route("/book_details/request/<int:book_id>", methods=["POST"])
@login_required
def request_book(book_id):
    book = Book.query.get_or_404(book_id)
    
    #Prevent from requesting own book
    if book.user_id == current_user.id:
        flash("You can not request your own book.", "warning")
        return redirect(url_for('books.book_details', book_id=book.id))

    #Prevent duplicate requests
    existing_request = BookRequest.query.filter_by(book_id=book.id, requester_id=current_user.id).first()
    if existing_request:
        flash("You have already requested this book!", "info")
        return redirect(url_for('books.my_requests', book_id=book.id))

    
    #Create a new request
    new_request = BookRequest(book_id=book.id, requester_id=current_user.id)
    db.session.add(new_request)
    db.session.commit()
    flash("Book request sent successfully!", "success")
    return redirect(url_for('books.book_details', book_id=book.id))


@books_bp.route("/my_requests")
@login_required
def my_requests():
    user_requests = BookRequest.query.filter_by(requester_id=current_user.id).all()
    return render_template("my-requests.html", requests=user_requests)

@books_bp.route("/my_donations")
@login_required
def my_donations():
    user_donations = Book.query.filter_by(user_id=current_user.id).order_by(Book.id.desc()).all()
    return render_template("my-donations.html", donations=user_donations)

@books_bp.route("/edit_book/<int:book_id>", methods=['GET', 'POST'])
def edit_book(book_id):
    book = Book.query.get_or_404(book_id)

    if request.method == 'POST':
        book.book_name = request.form['book_name']
        book.book_author = request.form['book_author']

        db.session.commit()
        flash('Book updated successfully!', 'success')
        return redirect(url_for('books.my_donations'))
    
    return render_template('edit-book.html', book=book)

@books_bp.route("/delete_book/<int:book_id>", methods=['POST'])
def delete_book(book_id):
    book = Book.query.get_or_404(book_id)

    db.session.delete(book)
    db.session.commit()
    flash("Book deleted successfully!", "success")
    return redirect(url_for('books.my_donations'))

app/routes/donate.py
import os
from flask import Blueprint, render_template, request, current_app, flash, session, redirect, url_for
from werkzeug.utils import secure_filename
from models import db, Book, BookRequest
from datetime import datetime
from flask_login import current_user, login_required


donate_bp = Blueprint("donate", __name__)

@donate_bp.route("/donate", methods=["GET", "POST"])
@login_required
def donate():
    # if 'user_id' not in session:
    #     flash("Please log in first")
    #     return redirect(url_for('auth.login'))
        
    if request.method == "POST":
        book_name = request.form["book_name"]
        book_author = request.form["book_author"]
        faculty = request.form["faculty"]
        book_image = request.files["book_image"]

        # Check is user has already donated the book
        existing_book = Book.query.filter_by(
            book_name=book_name,
            book_author=book_author,
            user_id=current_user.id
        ).first()

        if existing_book:
            flash("You have already donated this book", "info")
            return redirect(url_for('donate.donate'))
    
        if book_image:
            # Make file safe and store it
            filename = secure_filename(book_image.filename)
            image_path = os.path.join("static/uploads", filename)
            book_image.save(os.path.join(current_app.root_path, image_path))
        else:
            image_path = None

        # Save to database
        new_book = Book(
            book_name = book_name,
            book_author = book_author,
            faculty = faculty,
            book_image = image_path,
            date_added = datetime.now(),
            user_id = current_user.id
            )

        db.session.add(new_book)
        db.session.commit()

        flash(f"{book_name} Book Donated Successfully!", "success")
    
    return render_template("donate.html")

app/routes/receive.py
import os
from flask import Blueprint, render_template, request, current_app, flash
from werkzeug.utils import secure_filename
from models import db, Book, BookRequest
from datetime import datetime
from flask_login import current_user, login_required

receive_bp = Blueprint("receive", __name__)

@receive_bp.route("/receive")
def receive():
    books = Book.query.all()  # later to  add search filtering
    return render_template("receive.html", books=books)

# @receive_bp.route("/book-details")
# def book_details(book_id):
#     # Fetch the book by ID
#     book = Book.query.get_or_403(book_id)
#     return render_template("book-details.html", book=book)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Donation</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

</head>
<header class="header">
    <div class="logo">Book Donation</div> 
    <div class="current-user">
        {% if current_user.is_authenticated %}
        <!-- <span>Welcome, {{ current_user.first_name}}! </span> -->
        <div class="current-user-display">{{current_user.first_name}}</div>
        <a href="{{ url_for('auth.logout') }}" type="button" class="button" id="main-loginBtn">Log Out</a> 
        {% else %}
        <a href="{{ url_for('auth.login') }}" type="button" class="button" id="main-loginBtn">Log In</a> 
        {% endif %}
    </div>
</header>

<div class="gobackBtn-wrapper">
    {% block goback %}
    <a class="gobackBtn" href="{{ url_for('index')}}">Go Back</a>
    {% endblock %}
</div>

 
<!-- Flash messages area -->
<div class="flash-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="flash-message flash-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>


<body>
    {% block body %}{% endblock %}
</body>
</html>

app/templates/book-details.html
<!-- This page is for book description. It will also have a comment -->
{% extends 'base.html' %}

{% block body %}

      <div class="main book-details-page">
        <div class="book-details-container">
          <h1>Book Details:</h1>

            <div class="book-card-details">
              {% if book.book_image %}
              <img src="{{ url_for('static', filename=book.book_image.split('static/')[-1]) }}">
              {% endif %}
              <div class="book-info">
                <h2 class="book-title">{{ book.book_name }}</h2>
                <p class="book-author"><b>Author:</b> {{ book.book_author }}</p>
                <p class="book-faculty"><b>Faculty:</b> {{ book.faculty }}</p>
                <p class="book-added"><b>Added on:</b> {{ book.date_added.strftime('%Y-%m-%d') }}</p>
              </div>
              <form action="{{ url_for('books.request_book', book_id=book.id) }}" method="POST"> 
              <button type="submit" class="requestBtn">Request This Book</button>
              </form>
            </div>

            <!-- Comment Section -->
            <div class="comment-section">
              <h2>Comments</h2>

              <form class="comment-form" action="{{ url_for('books.add_comment', book_id=book.id)}}" method="POST">
                <textarea name="comment_content" placeholder="Write your comment here..." required></textarea>
                <button type="submit" class="submit-commentBtn">Post Comment</button>
              </form>

              <div class="comment-list">
                {% for comment in book.comments %}
                <div class="comment">
                  <p><strong>{{ comment.user.first_name }}: </strong>{{ comment.comment_content }}</p>
                  <small>{{ comment.timestamp.strftime('%Y-%m-%d %H:%M') }}</small>

                  <div class="comment-actions">
                    <button class="likeBtn">Like</button>
                    <button class="replyBtn">Reply</button>
                  </div>
                  
                  <form id="reply-form-{{ comment.id }}" class="reply-form" action="{{ url_for('books.reply', comment_id = comment.id) }}" method="POST" style="display:none;">
                  
                    <textarea name="reply_content" placeholder="Write your reply..." required></textarea>
                    <button type="submit">Post Reply</button>
                  </form>
                  <p>-------------------</p>

                  <div class="comment-replies">
                    {% for reply in comment.replies %}
                      <div class="reply">
                        <p><strong>{{ reply.user.first_name }}</strong>: {{ reply.reply_content}}</p>
                        <small>{{ reply.timestamp.strftime('%Y-%m-%d %H:%M') }}</small>
                      </div>
                    {% endfor %}
                  </div>

                </div>
                {% else %}
                <p>No comments yet!</p>
                {% endfor %}
              </div>
              
            </div>
        </div>

      </div>

{% endblock %}

app/templates/book-quality.html
{% extends 'base.html' %}

{% block body%}

    <div class="main book-quality-page">
        <div class="book-quality-container">
            <h1>Available Books:</h1>
            <div class="book-quality-card">

                <div class="book-card" data-title="Book A" data-faculty="Engineering">
                    <img src="img/books/book-a.png" alt="Book A">
                    <div>
                        <div class="book-title">Book A</div>
                        <button class="requestBtn">Request Button</button>
                    </div>
                </div>
                                <div class="book-card" data-title="Book A" data-faculty="Engineering">
                    <img src="img/books/book-a.png" alt="Book A">
                    <div>
                        <div class="book-title">Book A</div>
                        <button class="requestBtn">Request Button</button>
                    </div>
                </div>
                                <div class="book-card" data-title="Book A" data-faculty="Engineering">
                    <img src="img/books/book-a.png" alt="Book A">
                    <div>
                        <div class="book-title">Book A</div>
                        <button class="requestBtn">Request Button</button>
                    </div>
                    
                </div>
            </div>

        </div>

    </div>


{% endblock %}

app/templates/donate.html
{% extends 'base.html' %}

{% block body %}
<div class="main donate-page">
    <div class="donate-page-container">
        <form class="find-book" action="{{ url_for('donate.donate') }}" method="POST" enctype="multipart/form-data">
            <h1>Donate a Book</h1>
            <label for="find-book">Enter Book Details:</label>
            <input type="text" name="book_name" placeholder="Enter Book Name:" required>
            <input type="text" name="book_author" placeholder="Enter Book Author" required>

            <div class="form-row">
              <label for="faculty">Choose Category:</label>
              <select name="faculty" id="faculty">
                <option value="">All Faculties</option>
                <option value="letters">School of Letters</option>
                <option value="education">School of Education</option>
                <option value="law">Faculty of Law</option>
                <option value="economics">Faculty of Economics</option>
                <option value="sceince">School of Science</option>
                <option value="medical">Medical School</option>
                <option value="dental">Dental School</option>
                <option value="pharm">School of Pharmaceutical Sciences</option>
                <option value="engineering">School of Engineering</option>
                <option value="science-technology">School of Environmental Science of Technology</option>
                <option value="agriculture">School of Agriculture</option>
                <option value="gdp">Discovery Program for Global Program</option>
            </select>
            </div>
            <div class="form-row">
            <label for="donate-book">Upload a Book Picture:</label>
            <input type="file" id="book-image" name="book_image" accept="image/*" required/>
            </div>
            <input class="donateBtn" type="submit" value="Donate">
            
        </form>
    </div>
</div>


{% endblock %}

app/templates/edit-book.html
{% extends 'base.html' %}

{% block body %}
<div class="edit-book-page">
    <div class="edit-book-container">
        <h1>Edit Book</h1>

        <form method='POST' action="{{ url_for('books.edit_book', book_id=book.id) }}">
            <label for="title">Title</label>
            <input type="text" name="book_name" value="{{ book.book_name }}" required>

            <label for="author">Author</label>
            <input type="text" name="book_author" value="{{ book.book_author }}" required>

            <!-- <label for="description">Description</label>
            <textarea id="description" name="description">{{ book.description }}</textarea> -->

            <button type="submit" class="requestBtn">Save Changes</button>
        </form>

    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block goback %}
{% endblock %}

{% block body %}
        <div class="main">
        <!-- <div id="header"></div>
        <script src="static/js/include.js"></script> -->
        <div class="welcome">
            <h1>Welcome to Book Donation</h1>
            <h2>What would you like to do today?</h2>
        </div>

        <div class="donate-receive">
            <div>
            <div class="donate">
                <h1>Donate a Book</h1>
                <h2>Share your books with others</h2>
                <a class="donateBtn" href="{{ url_for('donate.donate') }}">Donate</a>
            </div>
            <div class="donate">
                <h1>My Donations</h1>
                <h2>List of donated books by you</h2>
                <a class="donateBtn" href="{{ url_for('books.my_donations') }}">Donations</a>
            </div>
            </div>

            <div>
                <div class="receive">
                    <h1>Receive a Book</h1>
                    <h2>Find and request books you need</h2>
                    <a class="receiveBtn" href="{{ url_for('receive.receive') }}">Receive</a>
               </div>
            <div class="receive">
                <h1>My Requests</h1>
                <h2>List of requested books by you</h2>
                <a class="receiveBtn" href="{{ url_for('books.my_requests') }}">Requests</a>
            </div>
            </div>

            
        </div>
        </div>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block body %}

  <div class="main login-page">
    <div class="login-container">

      <form class="login" action= "{{ url_for('auth.login') }}" method="POST">
        <h1>Log In</h1>
        <!-- <label for="email">Email:</label> -->
        <input type="email" id="email" name="email" placeholder="Email" required>

        <!-- <label for="password">Password:</label> -->
        <input type="password" id="password" name="password" placeholder="Password">

        <input class="loginBtn" type="submit" value="Log In">
        <p class="signup-prompt">Don't have an account? <a href="{{ url_for('auth.signup') }}">Sign Up</a></p>
      </form>
    </div>

  </div>

{% endblock %}

app/templates/my-donations.html
{% extends 'base.html' %}
{% block body %}
<div class="my-requests-page">
    <div class="my-requests-container">
        <h1>My Donated Books: </h1>
        {% if donations %}
        <div class="my-requests-list">
            {% for donation in donations %}
            <div class="my-requests-card">

                <img src="{{ url_for('static', filename=donation.book_image.split('static/')[-1])}}">
                <div class="my-requests-book-info">
                    <div class="book-title">{{ donation.book_name }}</div>
                    <div class="book-author">{{ donation.book_author }}</div>
                    <div class="book-faculty">{{ donation.faculty}}</div>
                    <div class="book-added">Donated Date: {{ donation.timestamp.strftime('%Y-%m-%d %H:%M') if donation.timestamp else 'N/A' }}
                    </div>
                </div>
                
                <a href="{{ url_for('books.edit_book', book_id=donation.id) }}" class="requestBtn">Edit</a>
                <form method="POST" action="{{ url_for('books.delete_book', book_id=donation.id)}}" >
                    <button type="submit" onclick="return confirm('Are you sure you want to delete {{ donations.book_name }}')">Delete</button>
                </form>

            
            </div> 
            {% endfor %}
        </div>
        {% else %}
        <p>You have not donated any book yet!</p>
        {% endif %}
    </div>
</div> 
{% endblock %}

app/templates/my-requests.html
{% extends 'base.html' %}
{% block body %}
<div class="my-requests-page">
    <div class="my-requests-container">
        <h1>My Requested Books: </h1>
        {% if requests %}
        <div class="my-requests-list">
            {% for req in requests %}
            <div class="my-requests-card">
                <img src="{{ url_for('static', filename=req.book.book_image.split('static/')[-1])}}">
                <div class="my-requests-book-info">
                    <div class="book-title">{{ req.book.book_name }}</div>
                    <div class="book-author">{{ req.book.book_author }}</div>
                    <div class="book-faculty">{{ req.book.faculty}}</div>
                    <div class="book-added">Requested time: {{ req.timestamp.strftime('%Y-%m-%d %H:%M') if req.timestamp else 'N/A' }}</div>
                    <div>Request Status: {{ req.status}}</div>
                </div>
            </div> 
            {% endfor %}
        </div>
        {% else %}
        <p>You have not requested any book yet!</p>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/receive.html
{% extends 'base.html' %}

{% block body %}
<div class="main receive-page">
  <div class="receive-container">
    
    <form class="find-book">
      <h1>Find a Book</h1>
      <label for="find-book">Search for book:</label>
      <input type="text" name="find_book" id="find-name" placeholder="Enter Book Name:" required>
      <input type="text" name="find_author" id="find-author" placeholder="Enter Book Author" required>
      
      <div class="form-row">
        <label for="faculty">Choose your faculty:</label>
        <select name="faculty" id="faculty">
          <option value="">All Faculties</option>
          <option value="letters">School of Letters</option>
          <option value="education">School of Education</option>
          <option value="law">Faculty of Law</option>
          <option value="economics">Faculty of Economics</option>
          <option value="sceince">School of Science</option>
          <option value="medical">Medical School</option>
          <option value="dental">Dental School</option>
          <option value="pharm">School of Pharmaceutical Sciences</option>
          <option value="engineering">School of Engineering</option>
          <option value="science-technology">School of Environmental Science of Technology</option>
          <option value="agriculture">School of Agriculture</option>
          <option value="gdp">Discovery Program for Global Program</option>
        </select>
      </div>
      <button class="searchBtn">Search</button>
    </form>

    <div class="book-grid" id="book-grid">
      {% for book in books %}
      <div class="book-card" data-title="{{ book.book_name}}" data-faculty="{{ book.faculty }}">
        {% if book.book_image %}
          <img src="{{url_for('static', filename=book.book_image.split('static/')[-1]) }}" alt="{{ book.book_name }}">
        {% endif %}
        
        <div class="book-info">
          <div class="book-title">{{ book.book_name }}</div>
          <div class="book-author">by {{ book.book_author }}</div>
          <div class="book-faculty">{{ book.faculty }}</div>
        </div>

        <a href="{{ url_for('books.book_details', book_id=book.id) }}" class="requestBtn">View Details</a>
      </div>
        {% endfor %}
    </div>
    
  </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block body %}

  <div class="main signup-page">    
      <div class="signup-container">
        
        <form class="signup" action = "{{ url_for('auth.signup') }}" method = "POST">
          <h1>Sign Up</h1>
          <input type="text" id="firstname" name="first_name" placeholder="First Name" required>
          <input type="text" id="lastname" name="last_name" placeholder="Last Name" required>
          <!-- Turn Faculty input into <select></select> and include dropdown -->
          <input type="text" id="faculty" name="faculty" placeholder="Faculty" required>
          <!-- <input type="number" id="school-year" name="school-year" placeholder="1 st year"> -->
          <!-- <select type="number" id="school-year" name="school-year" placeholder="Choose your school year:">
            <option>1st year</option>
            <option>2nd year</option>
            <option>3rd year</option>
          </select> -->



          <!-- <label for="email">Email:</label> -->
          <input type="email" id="email" name="email" placeholder="Email" required >

          <!-- <label for="password">Password:</label> -->
          <input type="password" id="password" name="password" placeholder="Password" required>

          <input class="signupBtn" type="submit" value="Sign Up">
          <!-- <p class="signup-prompt">Don't have an account? <a href="signup.html">Sign Up</a></p> -->
       </form>
     </div>

  </div>

{% endblock %}